### ISSUE TITLE
MiFlora support

### ISSUE THREAD

**Issue by adrianmihalko** [Justinb81/domoticz-flower-power#1]
Dear developer,

Thanks for your great project. I can receive data from my Flower Power. You mention Mi Flora support at the end of readme, but it's not clear to me: fp2dom.js can handle Xiaomi MiFlora too, or how it is possible to receive data from MiFlora?

Regards,
Adrian

**Comment by adrianmihalko** [comment]
Ahhh, after 12 hours of working (runned at every 15 minutes), it fails to read data:

[root@orangepizero:~/domoticz-flower-power# node ./FP2DOM.js a0143d7d9338
Processing: a0143dxxxxxx
serial id of this flowerpower : a0143dxxxxxx
connectAndSetup
disconnected!](url)

In lescan I see the device + the official FP app works:

[root@orangepizero:~/domoticz-flower-power# sudo hcitool lescan
LE Scan ...
A0:14:3D:XX:XX:XX
A0:14:3D:XX:XX:XX Flower power 9338](url)

Battery is at 38%.

**Comment by adrianmihalko** [comment]
+one more question: you use mol/m²/d as lighting unit. It is possible to convert this into lux (as it is in the official app)?

**Comment by Justinb81** [comment]
I started miflora support, but not uploaded yet because it is pretty unreliable to have all of the miflora's respond. I haven't had the time to continue work on that.
